# Generated by Django 4.2.5 on 2023-09-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aprendices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('documento', models.PositiveIntegerField()),
                ('typeDocumento', models.CharField(max_length=2)),
                ('ficha', models.PositiveIntegerField()),
            ],
        ),
    ]
