# Generated by Django 4.2.5 on 2023-09-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aprendices_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendices',
            name='typeDocumento',
            field=models.CharField(max_length=3),
        ),
    ]
